name: CI/CD Pipeline

permissions:
  issues: write

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - main
            - develop

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Java
              run: |
                sudo apt-get update
                sudo apt-get install -y openjdk-11-jre
                java -version

            - name: Cache frontend dependencies
              uses: actions/cache@v4
              with:
                path: frontend/node_modules
                key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
                restore-keys: ${{ runner.os }}-frontend-

            - name: Install frontend dependencies
              run: |
                  cd frontend
                  npm install

            - name: Setup Firebase Emulator for Frontend
              run: |
                  npm install -g firebase-tools
                  cd frontend
                  firebase emulators:start --only firestore &
                  sleep 15 # Increased wait time

            - name: Run Jest Unit Tests for React Components
              run: |
                  cd frontend
                  npm run test -- --coverage
              env:
                  CI: true
                  FIRESTORE_EMULATOR_HOST: localhost:8080
                  REACT_APP_FIREBASE_API_KEY: "AIzaSyCdD6bwFBYyTOikoF-oHrYvPTWrRH-gqeQ"
                  REACT_APP_FIREBASE_AUTH_DOMAIN: "furniture-ecommerce-435809.firebaseapp.com"

            - name: Archive frontend test coverage
              uses: actions/upload-artifact@v4
              with:
                name: frontend-coverage
                path: frontend/coverage

            - name: Cache backend dependencies
              uses: actions/cache@v4
              with:
                path: backend/node_modules
                key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
                restore-keys: ${{ runner.os }}-backend-

            - name: Install backend dependencies
              run: |
                  cd backend
                  npm install

            - name: Check and Free Port 9090
              run: |
                sudo lsof -i :9090 || true
                sudo kill -9 $(lsof -t -i :9090) || true

            - name: Setup Firebase Emulator for Backend
              run: |
                npm install -g firebase-tools
                cd backend
                firebase emulators:start --only firestore --no-localhost &
                sleep 30 

            - name: Run Jest Unit Tests for NodeJS API
              run: |
                  cd backend
                  npm run test -- --coverage
              env:
                  CI: true
                  FIRESTORE_EMULATOR_HOST: localhost:9090
                  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
                
            - name: Archive backend test coverage
              uses: actions/upload-artifact@v4
              with:
                name: backend-coverage
                path: backend/coverage

    integration-test:
        runs-on: ubuntu-latest
        needs: unit-test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"

            - name: Install Java
              run: |
                sudo apt-get update
                sudo apt-get install -y openjdk-11-jre
                java -version

            - name: Cache backend dependencies
              uses: actions/cache@v4
              with:
                path: backend/node_modules
                key: ${{ runner.os }}-backend-${{ hashFiles('backend/package-lock.json') }}
                restore-keys: ${{ runner.os }}-backend-

            - name: Install backend dependencies
              run: |
                  cd backend
                  npm install

            - name: Check and Free Port 9090
              run: |
                sudo lsof -i :9090 || true
                sudo kill -9 $(lsof -t -i :9090) || true

            - name: Setup Firebase Emulator
              run: |
                npm install -g firebase-tools
                cd backend
                firebase emulators:start --only firestore &
                sleep 15 # Increased wait time

            - name: Run Supertest Integration Tests
              run: |
                  cd backend
                  npm run test:integration
              env:
                  FIRESTORE_EMULATOR_HOST: localhost:9090
                  CI: true
                  FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}

    security-scan:
        runs-on: ubuntu-latest
        needs: integration-test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Initialize CodeQL
              uses: github/codeql-action/init@v3
              with:
                  languages: javascript
                  queries: security-and-quality

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@v3

    notify:
      runs-on: ubuntu-latest
      needs: [unit-test, integration-test, security-scan]
      if: failure()
      steps:
          - name: Create issue on failure
            uses: actions/github-script@v7
            with:
                script: |
                    github.rest.issues.create({
                      owner: context.repo.owner,
                      repo: context.repo.repo,
                      title: 'CI/CD Pipeline Failure',
                      body: 'The CI/CD pipeline failed. Please check the logs for details.\n\nRun ID: ${{ github.run_id }}',
                      labels: ['pipeline-failure']
                    })
